# Generated by Django 5.2 on 2025-04-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
